### ISSUE TITLE
workspace_min_width is nonexistent

### ISSUE THREAD

**Issue by romeq** [jbenden/i3-gaps-rounded#1]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

`workspace_min_width` is nonexistent, even though `i3-gaps-rounded` should be a __fork__ of i3. Why is it removed?

## Expected Behavior

`workspace_min_width` should exist

## Reproduction Instructions

including `workspace_min_width` when configuring `bar` in `i3/config` 

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
</pre>

<details><summary>Config file</summary><pre>
</pre>
</details>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version:
- Are you using a compositor (e.g., xcompmgr or compton):
</pre>

**Comment by jbenden** [comment]
Hi,

This option should be available and does appear in the source code, under the scope of `bar` - [here](https://github.com/jbenden/i3-gaps-rounded/blob/4587b938e57c263f128f1e3813bf71de1b04b980/src/config_directives.c#L893).

Also, not sure of the complaints about a `fork`...? This is a personal fork of [i3-gaps](https://github.com/Airblader/i3), not of i3. I created this repository for myself. If it finds itself useful to others then awesome!

Thanks,
-Joe

**Comment by romeq** [comment]
Thanks for response, and sorry for my rude attitude. 

Yep, it seems to be in the source code. I don't really understand why is it complaining about not finding `workspace_min_width` on my machine.

**Comment by jbenden** [comment]
Hum...

Please ensure that the binary and source code, namely the commit and branch are all correct.

If that's all good, I can try and debug it soon for you...

**Comment by romeq** [comment]
Sure. I was bust with exams this week, but I'll try to check those today.
Thanks.

**Comment by jbenden** [comment]
If this is still an issue then please re-open. Thanks!
